// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkrgvtperebgoqivoenf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcmd2dHBlcmViZ29xaXZvZW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTk4MDksImV4cCI6MjA2OTI5NTgwOX0.JoKBNm2mmRnbInVK8ID-8lkUpjEE4533cFnrY-rj81s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});